POST https://solid-space-garbanzo-wr957qw6qjrg39gxx-3000.app.github.dev/login HTTP/1.1
content-type: application/json

{
    "email": "hamuha330@gmail.com",
    "password": "password"
}

<!--curl ifconfig.me-->